[workspace]
authors = ["Luthfi <luthfillahatar@gmail.com>"]
channels = ["conda-forge", "pytorch"]
name = "ER-RAG"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pytorch = ">=2.8.0,<3"
transformers = ">=4.40.2,<5"
pandas = ">=2.3.3,<3"
numpy = "<2"
packaging = "<24"
huggingface_hub = "<0.23.0"
async-timeout = "<5"
intel-openmp = ">=2024.2.1,<2025"
python-dotenv = ">=1.2.2,<2"
pyarrow = ">=20.0.0,<21"
scikit-learn = ">=1.7.2,<2"
sentence-transformers = ">=3.2.0,<4"
ipykernel = ">=7.2.0,<8"
regex = ">=2026.3.32,<2027"
tqdm = ">=4.67.3,<5"

[pypi-dependencies]
ollama = ">=0.6.1, <0.7"
loguru = ">=0.7.3, <0.8"
openai = ">=2.30.0, <3"
langchain = ">=0.1.15, <0.2"
langchain-community = "==0.0.32"
langchain-core = "==0.1.41"
rank-bm25 = ">=0.2.2, <0.3"
nltk = "*"
sentencepiece = ">=0.2.1, <0.3"
beautifulsoup4 = ">=4.14.3, <5"
flagembedding = "==1.2.9"
chromadb = ">=1.5.5, <2"
torch = "*"
transformers = "*"
tqdm = "*"
pandas = "*"
numpy = "*"
requests = "*"
